version: '3'
services:
  db:
    image: postgres:12
    restart: always
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: nestjs
    container_name: postgres-db